theme: jekyll-theme-slate

# (опционально, если хочешь стили или логотипы)
title: "1st.Partners – Semantic Playbook"
description: "LLM Visibility Strategy & Ontology Resources"

defaults:
  - scope:
      path: ""
    values:
      layout: page

